import homepage from '../assets/homepage.png';
import homepage1 from '../assets/homepage1.png';

const picture = {
  home : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455059/Isioma_project/work/home_jclknt.jpg',
  menu : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697637015/Isioma_project/work/menu_e3d5xf.png',
  homepage : homepage,
  homepage1 : homepage1,
  facebook : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455019/Isioma_project/work/facebook_egls0e.png',
  family : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455020/Isioma_project/work/family_g7hhxc.webp',
  logo : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697637014/Isioma_project/work/logo_la1hww.png',
  hotel : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455061/Isioma_project/work/hotel_rac8ha.jpg',
  hotel1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455062/Isioma_project/work/hotel1_rmsfc6.jpg',
  houseA1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455062/Isioma_project/work/houseA1_tqrhkp.jpg',
  cancel : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455019/Isioma_project/work/cancel_o0xflr.png',
  houseA : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455062/Isioma_project/work/houseA_qjxkri.webp',
  houseBA1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697472311/Isioma_project/work/houseBA1_zuqgox.jpg',
  houseBA2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455063/Isioma_project/work/houseBA2_l5vzgw.jpg',
  houseB2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455063/Isioma_project/work/houseB2_hqbcbg.jpg',
  houseB : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455063/Isioma_project/work/houseB_ionrzt.jpg',
  houseB1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455063/Isioma_project/work/houseB1_hbhxnq.jpg',
  houseBA : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455063/Isioma_project/work/houseBA_vlm1yz.jpg',
  houseBB : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455064/Isioma_project/work/houseBB_gisk8o.jpg',
  houseBC : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455064/Isioma_project/work/houseBC_i88lrr.jpg',
  houseBD : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455065/Isioma_project/work/houseBD_wyzgqi.jpg',
  houseBE : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455066/Isioma_project/work/houseBE_zf6dbk.jpg',
  gen5  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455058/Isioma_project/work/gen5_nbpnrj.jpg',
  houseBF : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455066/Isioma_project/work/houseBF_wijitm.jpg',
  houseC : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455067/Isioma_project/work/houseC_jxwgfo.jpg',
  houseC1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455067/Isioma_project/work/houseC1_wsowei.jpg',
  houseC2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455068/Isioma_project/work/houseC2_dscsyu.jpg',
  houseD : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455068/Isioma_project/work/houseD_fziorn.jpg',
  houseD1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455068/Isioma_project/work/houseD1_iczn9y.jpg',
  houseH : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseH_lanhtc.webp',
  houseG : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseG_tywgby.jpg',
  houseH1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseH1_ci5owb.jpg',
  houseF : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseF_r8csun.jpg',
  houseG1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseG1_g8veck.jpg',
  gen1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gen1_gfa26k.jpg',
  gen2  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455057/Isioma_project/work/gen2_qkmzyi.jpg',
  gen3  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455057/Isioma_project/work/gen3_elcpef.jpg',
  gen4  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455057/Isioma_project/work/gen4_htnzjw.jpg',
  houseG2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455226/Isioma_project/work/houseG2_vljxkl.jpg',
  houseD3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseD3_avr0ud.jpg',
  houseE1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseE1_qhtlyt.jpg',
  houseD2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseD2_ndwecl.jpg',
  houseE : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseE_qegohg.jpg',
  houseI : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseI_lb7ezj.jpg',
  houseI1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseI1_aojtmf.jpg',
  houseI2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455227/Isioma_project/work/houseI2_pjzh6k.jpg',
  houseK : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455228/Isioma_project/work/houseK_ijttxx.jpg',
  houseK1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455228/Isioma_project/work/houseK1_zbsl7y.jpg',
  houseM : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455228/Isioma_project/work/houseM_qhkkiy.jpg',
  houseL : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455228/Isioma_project/work/houseL_vfusqd.jpg',
  houseN : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455228/Isioma_project/work/houseN_ok8b99.jpg',
  houseN1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455229/Isioma_project/work/houseN1_lhbfd9.jpg',
  houseO : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455229/Isioma_project/work/houseO_aws8ne.jpg',
  houseO1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455230/Isioma_project/work/houseO1_cumpkg.jpg',
  houseO2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455230/Isioma_project/work/houseO2_ywvdmb.jpg',
  gallery1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455019/Isioma_project/work/gallery1_wvvmxy.jpg',
  gallery2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697472310/Isioma_project/work/gallery2_hpl7kh.jpg',
  gallery3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455020/Isioma_project/work/gallery3_aaipms.webp',
  gallery4 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455022/Isioma_project/work/gallery4_dr0v0n.jpg',
  gallery5 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455040/Isioma_project/work/gallery5_wyvmao.jpg',
  gallery6 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455055/Isioma_project/work/gallery6_qfj01l.webp',
  gallery7 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery7_amfdgd.jpg',
  gallery8A : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery8A_r0h4hu.jpg',
  gallery8B : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery8B_twn97e.jpg',
  gallery8 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery8_oird3a.jpg',
  gallery9 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery9_qbte7j.jpg',
  gallery9A : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery9A_at2wqv.jpg',
  gallery9B : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455056/Isioma_project/work/gallery9B_x2h7ed.jpg',
  houseP : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455231/Isioma_project/work/houseP_sav6ak.png',
  houseP1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455231/Isioma_project/work/houseP1_mvplhv.jpg',
  houseQ : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455231/Isioma_project/work/houseQ_dam87g.jpg',
  houseR : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455231/Isioma_project/work/houseR_j7la7e.jpg',
  houseS : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455232/Isioma_project/work/houseS_jah9ux.jpg',
  houseS2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455232/Isioma_project/work/houseS2_uyeecf.jpg',
  houseS3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455232/Isioma_project/work/houseS3_cz4mn5.jpg',
  houseS1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455232/Isioma_project/work/houseS1_ncrbwt.jpg',
  houseV2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455233/Isioma_project/work/houseV2_jlhned.jpg',
  houseV : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455233/Isioma_project/work/houseV_tlo8fy.jpg',
  houseV3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455233/Isioma_project/work/houseV3_quus8r.jpg',
  houseV1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455233/Isioma_project/work/houseV1_mpkgbv.jpg',
  houseW : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455234/Isioma_project/work/houseW_ckonsa.jpg',
  houseW1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455234/Isioma_project/work/houseW1_uoi856.jpg',
  houseW2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455234/Isioma_project/work/houseW2_fer5aq.jpg',
  houseW3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455235/Isioma_project/work/houseW3_vadadr.jpg',
  houseX : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455235/Isioma_project/work/houseX_cfyuwm.jpg',
  houseX1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455235/Isioma_project/work/houseX1_xhklfe.webp',
  houseX3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455236/Isioma_project/work/houseX3_emspz6.jpg',
  houseX2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455236/Isioma_project/work/houseX2_nmvpxb.jpg',
  houseY : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455236/Isioma_project/work/houseY_dxuxkv.jpg',
  houseY1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455236/Isioma_project/work/houseY1_yawcvm.jpg',
  houseZ : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455237/Isioma_project/work/houseZ_vbwckn.jpg',
  houseZ1 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455237/Isioma_project/work/houseZ1_bju0il.jpg',
  houseZ2 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455237/Isioma_project/work/houseZ2_naf1sj.jpg',
  houseZ3 : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455237/Isioma_project/work/houseZ3_crwaz0.jpg',
  twitter : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455239/Isioma_project/work/twitter_njn3rw.png',
  instagram : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455238/Isioma_project/work/instagram_gt63ic.png',
  linkedin : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455238/Isioma_project/work/linkedin_zxht6a.png',
  star  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455239/Isioma_project/work/star_wb4dvu.png',
  wow  : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455241/Isioma_project/work/wow_s7fgmt.png',
  discount : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455019/Isioma_project/work/discount_cft3zw.png',
  discant : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455019/Isioma_project/work/discant_xa5344.png',
  cancels : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455020/Isioma_project/work/cancels_ydqs2v.png',
  video   : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697455242/Isioma_project/work/video_sindks.png',
  welcome : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697475097/Isioma_project/work/welcome_eby8li.jpg',
  sent : 'https://res.cloudinary.com/dneejvhch/image/upload/v1697624602/Isioma_project/work/Group_211_wolujt.png',
}


const Houses = [
  {
    title: "Property 1",
    price: "NGN 80,000,000",
    location: "Alimosho, Lagos",
    image: picture.gallery1,
    description:"5 bedroom Fully duplex Installed . Land Size 1200Sam, C of O guaranteed ",
    film: picture.gallery1,
  photos: [picture.gallery1, picture.houseE1, picture.houseD, picture.houseO],
  },
  {
    title: "Property 2",
    price: "NGN 250,000,000",
    location: "Garki, Abuja",
    image: picture.gallery2,
    description:"5 bedroom Fully duplex with BQ Installed solar light. enough parking space, C of O guaranteed ",
    film: picture.gallery2,
    photos: [picture.gallery2, picture.houseZ1, picture.houseI2, picture.houseX],
  },
  {
    title: "Property 3",
    price: "NGN 20,000,000",
    location: "Shomolu, Lagos",
    image: picture.gallery3,
    description:"3 bedroom Fully Bungalow fully fenced. Land Size 2 plots, C of O guaranteed ",
    film: picture.gallery3,
    photos: [picture.gallery3, picture.houseN1, picture.houseS, picture.houseG1],
  },
  {
    title: "Property 4",
    price: "NGN 25,000,000",
    location: "Surulere, Lagos",
    image: picture.gallery4,
    description:"4 bedroom Fully Bungalow fully fenced. Land Size 2 plots, C of O guaranteed ",
    film: picture.gallery4,
    photos: [picture.gallery4, picture.houseO1, picture.houseC2, picture.houseE1],
  },
  {
    title: "Property 5",
    price: "NGN 350,000,000",
    location: "Maitama, Abuja",
    image: picture.gallery5,
    description:"8 bedroom, 2 sittin rooms Mansion with 2 BQ rooms Installed solar light. Land Size 1500Sam, C of O guaranteed ",
    film: picture.gallery5,
    photos: [picture.gallery5, picture.houseY1, picture.houseQ, picture.houseH1],
  },
  {
    title: "Property 6",
    price: "NGN 45,000,000",
    location: "Lekki-Phase-1, Lagos",
    image: picture.gallery6,
    description:"5 bedroom Fully duplex with  solar light. Land Size 3 plots, C of O guaranteed ",
    film: picture.gallery6,
    photos: [picture.gallery6, picture.houseP1, picture.houseBA, picture.houseA1],
  },
];

const Lands = [
  {
    title: "Property 7",
    price: "NGN 2,000,000,000",
    location: "Badagry, Lagos",
    image: picture.home,
    description:"Open Land facing the road fully cleared. Land Size 12 Acres, C of O guaranteed ",
    film: picture.home,
    photos: [picture.home, picture.home, picture.home, picture.home],
  },
  {
    title: "Property 8",
    price: "NGN 150,000,000",
    location: "Festac, Lagos",
    image: picture.gallery7,
    description:"5 bedroom Fully duplex with BQ Installed solar light. Land Size 1200Sam, C of O guaranteed ",
    film: picture.gallery7,
    photos: [picture.gallery7, picture.houseA, picture.houseI2, picture.gen5],
  },
  {
    title: "Property 9",
    price: "NGN 15,000,000",
    location: "Port-hacourt",
    image: picture.gallery8,
    description:"5 bedroom Fully Bungalow under construction but fully roofed. Land Size 2 and half plots, Complete papers ",
    film: picture.gallery8,
    photos: [picture.gallery8, picture.gallery8A, picture.gallery8B, picture.gen3],
  },
  {
    title: "Property 10",
    price: "NGN 35,000,000",
    location: "Ugbowo, Benin-city Benin",
    image: picture.gallery9,
    description:"5 bedroom m Fully Bungalow. large compound with enough parking space. Land Size 3 Plots, C of O guaranteed ",
    film: picture.gallery9,
    photos: [picture.gallery9, picture.gallery9A, picture.gallery9B, picture.houseS],
  }
];


const testimonials = [
  {
    name: "Johnson Okafor",
    title: "Surgeon",
    text: "My expereince with this company is second to none. I have been more satisfied.",
    image: picture.home,
  },
  {
    name: "picture.House 1",
    title: "NGN 200,000,000",
    text: "Lekki, Lagos",
    image: picture.home,
  },
  {
    name: "picture.House 2",
    title: "NGN 200,000,000",
    text: "Lekki, Lagos",
    image: picture.home,
  },
  {
    name: "picture.House 4",
    title: "NGN 200,000,000",
    text: "Lekki, Lagos",
    image: picture.home,
  },
  {
    name: "picture.House 5",
    title: "NGN 200,000,000",
    text: "Lekki, Lagos",
    image: picture.home,
  },
  {
    name: "picture.House 3",
    title: "NGN 200,000,000",
    text: "Lekki, Lagos",
    image: picture.home,
  },
];

const Card = [
  {
    title: "5 bedroom Fully duplex",
    description:
      "5 bedroom Fully duplex with BQ Installed solar light. Land Size 1200Sam, C of O guaranteed ",
    price: "700 Million Naira",
    location: "Lekki, Lagos",
    image: picture.houseI,
    film: picture.houseI,
    availability: "Available",
    photos: [picture.houseI, picture.houseI1, picture.houseI2, picture.gen1],
  },
  {
    title: "Fully Serviced and Furnished 4 bedroom with 1 room BQ",
    description:
      "Fully Serviced and Furnished 4 bedroom with 1 room BQ.Personal swimming pool, CCTV, 15kva generator, 3.5 Kva inverter. ",
    price: "1.5 Million Naira rent per annum ( 2years payment is applied)",
    location: "110 Ebitu Ukiwe street, Jabi, Abuja.",
    image: picture.houseB,
    film: picture.houseB,
    availability: "Available",
    photos: [picture.houseB, picture.houseB1, picture.houseB2, picture.gen1],
  },
  {
    title: "8 units of 2 bedroom block of flats",
    description:
      "8 units of 2 bedroom block of flats.  Land Size 800Sam, C of O guaranteed",
    price: "550 Million Naira",
    location: " Gilmor Jahi, ABUJA",
    image: picture.houseF,
    film: picture.houseF,
    availability: "Available",
    photos: [picture.houseF, picture.gen2, picture.gen3, picture.gen4],
  },
  {
    title: "8 bedrooms Duplex and 3 sitting rooms",
    description:
      "8 bedrooms Duplex and 3 sitting rooms, a swimming pool and enough parking space,  C of O guaranteed.",
    price: "2 Billion Naira",
    location: "Maitama by Yoruba mosque, Abuja ",
    image: picture.houseC,
    film: picture.houseC,
    availability: "In Construction",
    photos: [picture.houseC, picture.houseC1, picture.houseC2, picture.houseB1],
  },

  {
    title: "5 bedroom fully detached duplex with 2 units of BQ",
    description:
      "5 bedroom fully detached duplex with 2 units of BQ Brand new and Serviced with A/C, C of O guaranteed.",
    price: "350 Million Naira",
    location: " Inside an Estate by Games village axis Kukwaba",
    image: picture.houseD,
    film: picture.houseD,
    availability: "Available",
    photos: [picture.houseD, picture.houseD1, picture.houseD2, picture.gen5],
  },

  {
    title: "4 bedroom spacious terrace duplex",
    description:
      "4 bedroom spacious terrace duplex, Serviced with A/C, 1 room BQ, C of O guaranteed.",
    price: " 200 Million Naira",
    location: "Jahi - Abuja",
    image: picture.houseH,
    film: picture.houseH,
    availability: "Available",
    photos: [picture.houseH, picture.houseH1, picture.houseC1, picture.houseC2],
  },

  {
    title: "Fully Serviced and Furnished 5 bedroom with 1 room BQ",
    description:
      "Fully Serviced and Furnished 5 bedroom with 1 room BQ.Personal swimming pool, CCTV, 15kva generator, 3.5 Kva inverter. ",
    price: "2.5 Million Naira rent per annum ( 2years payment is applied)",
    location: "110 Ebitu Ukiwe street, Gwagwalada, Abuja.",
    image: picture.houseK,
    film: picture.video,
    availability: "Available",
    photos: [picture.houseK, picture.houseC1, picture.houseC2, picture.houseK1],
  },

  {
    title: "4 units of 2 bedroom block of flats",
    description:
      "4 units of 2 bedroom block of flats.  Land Size 800Sam, C of O guaranteed",
    price: "350 Million Naira",
    location: "  ABUJA",
    image: picture.houseA,
    film: picture.video,
    availability: "Available",
    photos: [picture.houseA, picture.houseA1, picture.houseH1, picture.houseB1],
  },
  {
    title: "12 bedrooms Duplex and 3 sitting rooms",
    description:
      "12 bedrooms Duplex and 3 sitting rooms, a swimming pool and enough parking space,  C of O guaranteed.",
    price: "2.5 Billion Naira",
    location: "Maitama by Yoruba mosque, Lokoja ",
    image: picture.houseE,
    film: picture.video,
    availability: "Available",
    photos: [picture.houseE, picture.houseE1, picture.houseC1, picture.houseH1],
  },
  {
    title: "8 bedroom fully detached duplex with 2 units of BQ",
    description:
      "8 bedroom fully detached duplex with 2 units of BQ Brand new, C of O guaranteed.",
    price: "550 Million Naira",
    location: "Block 5, 21 road, FESTAC, Lagos",
    image: picture.houseG,
    film: picture.houseG,
    availability: "Available",
    photos: [picture.houseG, picture.houseG1, picture.houseG2, picture.houseI1],
  },
  {
    title: "Hotel Available",
    description:
      "56- Bedrooms all ensuite, stunning furnishings, fully equipped.The lounge/Restaurant equipped with state-of-the-art furniture and furnishings,Two Conference Halls suitable for all events. The SkyView Rooftop Lounge/Restaurant/Events, The Laundry department equipped with state-of-the-art equipment, Compound size👉2000sqm",
    price: "900 million",
    location: "Abuja",
    image: picture.hotel,
    film: picture.hotel,
    availability: "Available",
    photos: [picture.hotel, picture.houseC1, picture.hotel1, picture.video],
  },
  {
    title: "6 bedroom spacious terrace duplex",
    description:
      "6 bedroom spacious terrace duplex, Serviced with A/C,a sitting room, a dining room, 2 room BQ, C of O guaranteed.",
    price: " 450 Million Naira",
    location: "GRA - Port-hacourt",
    image: picture.houseL,
    film: picture.houseL,
    availability: "Available",
    photos: [picture.houseL, picture.houseC, picture.houseC1, picture.houseE],
  },
  {
    title: "8 units of 2 bedroom block of flats",
    description: "2 units of 4 bedroom block of flat, C of O guaranteed",
    price: "350 Million Naira",
    location: " Surulere, lagos",
    image: picture.houseM,
    film: picture.houseM,
    availability: "Available",
    photos: [picture.houseM, picture.houseO, picture.houseE1, picture.houseBA],
  },
  {
    title: "4 bedroom fully detached Bungalow",
    description: "4 bedroom fully detached Bungalow, C of O guaranteed.",
    price: "60 Million Naira",
    location: "Block 30, suleman street, Alimosho, Lagos",
    image: picture.houseN,
    film: picture.houseN,
    availability: "under Construction",
    photos: [picture.houseN, picture.houseN1, picture.houseBC, picture.houseS],
  },
  {
    title: "2 bedroom fully detached flat",
    description: "2 bedroom fully detached flat Brand new, C of O guaranteed.",
    price: "50 Million Naira",
    location: "Abeokuta, Ogun",
    image: picture.houseO,
    film: picture.houseO,
    availability: "Available",
    photos: [picture.houseO1, picture.houseO2, picture.houseBC, picture.houseO],
  },
  {
    title: "4 bedroom fully detached duplex with 2 unit of BQ",
    description:
      "4 bedroom fully detached duplex with 1 unit of BQ Brand new and Serviced with A/C, C of O guaranteed.",
    price: "350 Million Naira",
    location: "Ado, Ajah, Lagos",
    image: picture.houseP,
    film: picture.houseP,
    availability: "Available",
    photos: [picture.houseP, picture.houseH1, picture.houseK1, picture.houseP1],
  },
  {
    title: "8 Bedrooms Mansion",
    description:
      "8 Bedrooms Mansion with A dining room, sitting room, 2 room BQ with enough parking space, C of O guaranteed.",
    price: " 1 Billion Naira",
    location: "Oniru, Victoria Island, Lagos",
    image: picture.homepage,
    film: picture.homepage,
    availability: "Available",
    photos: [picture.homepage, picture.houseQ, picture.houseC, picture.houseE],
  },
  {
    title: "5 bedroom fully detached duplex with 2 units of BQ",
    description:
      "5 bedroom fully detached duplex with 2 units of BQ Brand new and Serviced with A/C, C of O guaranteed.",
    price: "550 Million Naira",
    location: " Inside Seaside Estate by Computer Village, Ikeja, Lagos",
    image: picture.houseR,
    film:  picture.houseR,
    availability: "Available",
    photos: [picture.houseQ, picture.houseC, picture.houseC1,  picture.houseR],
  },
  {
    title: "Fully Serviced and Furnished 4 bedroom with 1 room BQ",
    description:
      "Fully Serviced and Furnished 4 bedroom with 1 room BQ.Personal swimming pool, CCTV, 15kva generator, 3.5 Kva inverter. ",
    price: "2.5 Million Naira rent per annum ( 2years payment is applied)",
    location: "Agungi, Lekki, Lagos",
    image: picture.houseS,
    film:  picture.houseS,
    availability: "Available",
    photos: [ picture.houseS,  picture.houseS1,  picture.houseS2,  picture.houseS3],
  },
  {
    title: "5 Bedroom Bungalow",
    description:
      "5 Bedrooms Bungalow with 1 sitting rooms 4 masters bedroom,  and free compound space,  (For Rent)",
    price: " 2 Million Naira",
    location: "Magodo Gra Phase 2 Estate Ikeja Lagos",
    image: picture.houseD,
    film: picture.houseD,
    availability: "Available",
    photos: [picture.houseD, picture.houseP1, picture.houseD3, picture.houseBA],
  },
  {
    title: "Hotel Lounge and Bar Available",
    description:
      "30- Bedrooms all ensuite, fully equipped.The lounge/Restaurant equipped with state-of-the-art furniture and furnishings, Conference Halls suitable for all events. Alfredo Lounge/Restaurant/Events, The Laundry department equipped with state-of-the-art equipment, Compound size👉1500sqm",
    price: "700 million",
    location: "Festac, Lagos",
    image: picture.hotel,
    film: picture.hotel,
    availability: "Available",
    photos: [picture.hotel, picture.houseC, picture.houseC1, picture.houseE],
  },
  {
    title: "12 Bedrooms Mansion",
    description:
      "12 Bedrooms Mansion with A dining room, 2 sitting rooms, 2 room BQ with enough parking space, C of O guaranteed.",
    price: " 1.5 Billion Naira",
    location: "Area 11, Garki, Abuja",
    image: picture.houseV,
    film: picture.houseV,
    availability: "Available",
    photos: [picture.houseV, picture.houseV1, picture.houseV2, picture.houseV3],
  },
  {
    title: "5 Bedrooms Duplex",
    description:
      "5 Bedrooms Duplex with 1 sitting room, 1 room BQ with enough parking space, C of O guaranteed.",
    price: " 450 Million Naira",
    location: "Allen-Avenue, Ikeja, Lagos",
    image: picture.houseW,
    film: picture.houseW,
    availability: "Available",
    photos: [picture.houseW, picture.houseW1, picture.houseW2, picture.houseW3],
  },
  {
    title: "4 Bedrooms Duplex and 1 sitting rooms",
    description:
      "4 Bedrooms Duplex with 1 sitting room with enough parking space, C of O guaranteed.",
    price: " 150 Million Naira",
    location: "Satellite-town, Lagos",
    image: picture.houseX,
    film: picture.houseX,
    availability: "Available",
    photos: [picture.houseX, picture.houseX1, picture.houseX2, picture.houseX3],
  },
  {
    title: "3 Bedroom Flat",
    description:
      "3 Bedrooms Flat with 1 sitting rooms,  and free compound space,  (For Rent)",
    price: " 1 Million Naira",
    location: "Maitama, Abuja",
    image: picture.houseY,
    film: picture.houseY,
    availability: "Available",
    photos: [picture.houseY, picture.houseY1, picture.houseI1, picture.houseB],
  },
  {
    title: "6 Bedrooms Duplex and 2 sitting rooms",
    description:
      "6 Bedrooms Duplex and 2 sitting rooms,  and enough parking space,  (For Rent)",
    price: "2.5 Million Naira (Annually)",
    location: "Ojudu-Berger, Ikeja, Lagos",
    image: picture.houseZ,
    film: picture.houseZ,
    availability: "Available",
    photos: [picture.houseZ, picture.houseZ1, picture.houseZ2, picture.houseZ3],
  },
  {
    title: "4 bedrooms Duplex",
    description:
      "4 bedrooms Duplex. 1 dining room, sitting room and enough parking space.",
    price: "200 Million Naira",
    location: "Ogba, Ikeja, Lagos",
    image: picture.houseBA,
    film: picture.houseBA,
    availability: "Available",
    photos: [picture.houseBA, picture.houseBA1, picture.houseBA2, picture.gen1],
  },
  {
    title: "Hotel Available",
    description:
      "76- Bedrooms all ensuite, stunning furnishings, fully equipped.The lounge/Restaurant equipped with state-of-the-art furniture and furnishings,Two Conference Halls suitable for all events. The SkyView Rooftop Lounge/Restaurant/Events, The Laundry department equipped with state-of-the-art equipment, Compound size👉2000sqm",
    price: "1.2 Billion",
    location: "Port-Hacourt",
    image: picture.houseBE,
    film: picture.houseBE,
    availability: "Available",
    photos: [picture.houseBE, picture.houseBF, picture.houseC1, picture.homepage],
  },
  {
    title: "2 bedroom fully detached flat",
    description: "2 bedroom fully detached flat Brand new, C of O guaranteed.",
    price: "70 Million Naira",
    location: "Block 30, 28 road, FESTAC, Lagos",
    image: picture.gallery6,
    film: picture.gallery6,
    availability: "Available",
    photos: [picture.gallery6, picture.houseP1, picture.houseBA, picture.houseA1],
  },
  {
    title: "6 bedrooms Duplex and 2 sitting rooms",
    description:
      "6 bedrooms Duplex and 2 sitting rooms,  and enough parking space,  C of O guaranteed.",
    price: "1.5 Billion Naira",
    location: "Maitama by Yoruba mosque, Kaduna ",
    image: picture.houseBD,
    film: picture.houseBD,
    availability: "Available",
    photos: [picture.houseBD, picture.houseBB, picture.houseB, picture.houseB1],
  },
];

const Feeds = [
  {
    date: "Johnson Okafor",
    title: "Surgeon",
    description:
      "My expereince with this company is second to none. I have been more satisfied.",
    image: picture.home,
  },
  {
    date: "House 1",
    title: "NGN 200,000,000",
    description: "Lekki, Lagos",
    image: picture.home,
  },
  {
    date: "House 2",
    title: "NGN 200,000,000",
    description: "Lekki, Lagos",
    image: picture.home,
  },
  {
    date: "House 4",
    title: "NGN 200,000,000",
    description: "Lekki, Lagos",
    image: picture.home,
  },
  {
    date: "House 5",
    title: "NGN 200,000,000",
    description: "Lekki, Lagos",
    image: picture.home,
  },
  {
    date: "House 3",
    title: "NGN 200,000,000",
    description: "Lekki, Lagos",
    image: picture.home,
  },
];

export default {picture, Houses, Lands, testimonials, Card, Feeds};
